/* link_test.cpp: links for testing IntraMine's autolinking.
The other file expected is elasticsearch_index_test.txt.
This file's view is generated by CodeMirror with links on demand, and the txt file's view
is custom but also with links on demand.
link_test by itself should not be a link.
*/

// We should have test_programs/link_test.cpp and "link_test.cpp" as links.
// "test_programs/link_test.cpp"

// test_programs/elasticsearch_index_test.txt
// "test_programs/elasticsearch_index_test.txt"
