# ext.pm: text and image file extensions supported by IntraMine. Extension can be matched
# in $text with or without a leading period, but the extension must be the last thing
# in the $text. All is case-insensitive.
# The lists for text extensions are generated by
# codemirror_extensions.pl, excepting .t, .pod, .bat, .docx, and .pdf. Note .h++ and .c++ are excluded.

package ext;
use warnings;
require Exporter;
use Exporter qw(import);

use strict;

# Text and image extensions. Includes .t .bat and .pod, excludes .docx and .pdf.
my $textExtensions = qr/\.(1|2|3|4|4th|5|6|7|8|9|BUILD|R|apl|asc|asn|asn1|aspx|b|bash|bat|bf|bzl|c|cc|cfg|cgi|cl|clj|cljc|cljs|cljx|cmake|cob|coffee|conf|cpp|cpy|cql|cr|cs|css|cxx|cyp|cypher|d|dart|def|diff|dtd|dyalog|dyl|dylan|e|ecl|edn|ejs|el|elm|erb|erl|f|f77|f90|f95|factor|feature|for|forth|fs|fth|fun|go|gradle|groovy|gss|h|haml|handlebars|hbs|hh|hpp|hs|htm|html|hx|hxml|hxx|in|ini|ino|intr|j2|jade|java|jinja|jinja2|jl|js|json|jsonld|jsp|jsx|ksh|kt|less|lhs|lisp|list|log|ls|ltx|lua|m|map|markdown|mbox|md|mkd|ml|mli|mll|mly|mm|mo|mps|msc|mscgen|mscin|msgenny|nb|nq|nsh|nsi|nt|nut|oz|p|pas|patch|pgp|php|php3|php4|php5|php7|phtml|pig|pl|pls|pm|pod|pp|pro|properties|proto|ps1|psd1|psm1|pug|pxd|pxi|py|pyw|pyx|q|r|rb|rq|rs|rst|s|sas|sass|scala|scm|scss|sh|sieve|sig|siv|slim|smackspec|sml|soy|sparql|spec|sql|ss|st|styl|sv|svg|svh|swift|t|tcl|tex|text|textile|toml|tpl|ts|tsx|ttcn|ttcn3|ttcnpp|ttl|txt|v|vb|vbs|vhd|vhdl|vtl|vue|webidl|xml|xquery|xsd|xsl|xu|xy|yaml|yml|ys|z80)$/i;
my $imageExtensions = qr/\.(png|gif|jpe?g|ico)$/i;
my $textExtensionsNoPeriod = qr/(1|2|3|4|4th|5|6|7|8|9|BUILD|R|apl|asc|asn|asn1|aspx|b|bash|bat|bf|bzl|c|cc|cfg|cgi|cl|clj|cljc|cljs|cljx|cmake|cob|coffee|conf|cpp|cpy|cql|cr|cs|css|cxx|cyp|cypher|d|dart|def|diff|dtd|dyalog|dyl|dylan|e|ecl|edn|ejs|el|elm|erb|erl|f|f77|f90|f95|factor|feature|for|forth|fs|fth|fun|go|gradle|groovy|gss|h|haml|handlebars|hbs|hh|hpp|hs|htm|html|hx|hxml|hxx|in|ini|ino|intr|j2|jade|java|jinja|jinja2|jl|js|json|jsonld|jsp|jsx|ksh|kt|less|lhs|lisp|list|log|ls|ltx|lua|m|map|markdown|mbox|md|mkd|ml|mli|mll|mly|mm|mo|mps|msc|mscgen|mscin|msgenny|nb|nq|nsh|nsi|nt|nut|oz|p|pas|patch|pgp|php|php3|php4|php5|php7|phtml|pig|pl|pls|pm|pod|pp|pro|properties|proto|ps1|psd1|psm1|pug|pxd|pxi|py|pyw|pyx|q|r|rb|rq|rs|rst|s|sas|sass|scala|scm|scss|sh|sieve|sig|siv|slim|smackspec|sml|soy|sparql|spec|sql|ss|st|styl|sv|svg|svh|swift|t|tcl|tex|text|textile|toml|tpl|ts|tsx|ttcn|ttcn3|ttcnpp|ttl|txt|v|vb|vbs|vhd|vhdl|vtl|vue|webidl|xml|xquery|xsd|xsl|xu|xy|yaml|yml|ys|z80)$/i;
my $imageExtensionsNoPeriod = qr/(png|gif|jpe?g|ico)$/i;
my $exactTextExtensionsNoPeriod = qr/^(1|2|3|4|4th|5|6|7|8|9|BUILD|R|apl|asc|asn|asn1|aspx|b|bash|bat|bf|bzl|c|cc|cfg|cgi|cl|clj|cljc|cljs|cljx|cmake|cob|coffee|conf|cpp|cpy|cql|cr|cs|css|cxx|cyp|cypher|d|dart|def|diff|dtd|dyalog|dyl|dylan|e|ecl|edn|ejs|el|elm|erb|erl|f|f77|f90|f95|factor|feature|for|forth|fs|fth|fun|go|gradle|groovy|gss|h|haml|handlebars|hbs|hh|hpp|hs|htm|html|hx|hxml|hxx|in|ini|ino|intr|j2|jade|java|jinja|jinja2|jl|js|json|jsonld|jsp|jsx|ksh|kt|less|lhs|lisp|list|log|ls|ltx|lua|m|map|markdown|mbox|md|mkd|ml|mli|mll|mly|mm|mo|mps|msc|mscgen|mscin|msgenny|nb|nq|nsh|nsi|nt|nut|oz|p|pas|patch|pgp|php|php3|php4|php5|php7|phtml|pig|pl|pls|pm|pod|pp|pro|properties|proto|ps1|psd1|psm1|pug|pxd|pxi|py|pyw|pyx|q|r|rb|rq|rs|rst|s|sas|sass|scala|scm|scss|sh|sieve|sig|siv|slim|smackspec|sml|soy|sparql|spec|sql|ss|st|styl|sv|svg|svh|swift|t|tcl|tex|text|textile|toml|tpl|ts|tsx|ttcn|ttcn3|ttcnpp|ttl|txt|v|vb|vbs|vhd|vhdl|vtl|vue|webidl|xml|xquery|xsd|xsl|xu|xy|yaml|yml|ys|z80)$/i;
my $exactImageExtensionsNoPeriod = qr/^(png|gif|jpe?g|ico)$/i;

# Includes .t .bat and .pod, also .docx and .pdf.
my $textDocxPdfExtensions = qr/\.(1|2|3|4|4th|5|6|7|8|9|BUILD|R|apl|asc|asn|asn1|aspx|b|bash|bat|bf|bzl|c|cc|cfg|cgi|cl|clj|cljc|cljs|cljx|cmake|cob|coffee|conf|cpp|cpy|cql|cr|cs|css|cxx|cyp|cypher|d|dart|def|diff|docx|dtd|dyalog|dyl|dylan|e|ecl|edn|ejs|el|elm|erb|erl|f|f77|f90|f95|factor|feature|for|forth|fs|fth|fun|go|gradle|groovy|gss|h|haml|handlebars|hbs|hh|hpp|hs|htm|html|hx|hxml|hxx|in|ini|ino|intr|j2|jade|java|jinja|jinja2|jl|js|json|jsonld|jsp|jsx|ksh|kt|less|lhs|lisp|list|log|ls|ltx|lua|m|map|markdown|mbox|md|mkd|ml|mli|mll|mly|mm|mo|mps|msc|mscgen|mscin|msgenny|nb|nq|nsh|nsi|nt|nut|oz|p|pas|patch|pdf|pgp|php|php3|php4|php5|php7|phtml|pig|pl|pls|pm|pod|pp|pro|properties|proto|ps1|psd1|psm1|pug|pxd|pxi|py|pyw|pyx|q|r|rb|rq|rs|rst|s|sas|sass|scala|scm|scss|sh|sieve|sig|siv|slim|smackspec|sml|soy|sparql|spec|sql|ss|st|styl|sv|svg|svh|swift|t|tcl|tex|text|textile|toml|tpl|ts|tsx|ttcn|ttcn3|ttcnpp|ttl|txt|v|vb|vbs|vhd|vhdl|vtl|vue|webidl|xml|xquery|xsd|xsl|xu|xy|yaml|yml|ys|z80)$/i;
my $textDocxPdfExtensionsNoPeriod = qr/(1|2|3|4|4th|5|6|7|8|9|BUILD|R|apl|asc|asn|asn1|aspx|b|bash|bat|bf|bzl|c|cc|cfg|cgi|cl|clj|cljc|cljs|cljx|cmake|cob|coffee|conf|cpp|cpy|cql|cr|cs|css|cxx|cyp|cypher|d|dart|def|diff|docx|dtd|dyalog|dyl|dylan|e|ecl|edn|ejs|el|elm|erb|erl|f|f77|f90|f95|factor|feature|for|forth|fs|fth|fun|go|gradle|groovy|gss|h|haml|handlebars|hbs|hh|hpp|hs|htm|html|hx|hxml|hxx|in|ini|ino|intr|j2|jade|java|jinja|jinja2|jl|js|json|jsonld|jsp|jsx|ksh|kt|less|lhs|lisp|list|log|ls|ltx|lua|m|map|markdown|mbox|md|mkd|ml|mli|mll|mly|mm|mo|mps|msc|mscgen|mscin|msgenny|nb|nq|nsh|nsi|nt|nut|oz|p|pas|patch|pdf|pgp|php|php3|php4|php5|php7|phtml|pig|pl|pls|pm|pod|pp|pro|properties|proto|ps1|psd1|psm1|pug|pxd|pxi|py|pyw|pyx|q|r|rb|rq|rs|rst|s|sas|sass|scala|scm|scss|sh|sieve|sig|siv|slim|smackspec|sml|soy|sparql|spec|sql|ss|st|styl|sv|svg|svh|swift|t|tcl|tex|text|textile|toml|tpl|ts|tsx|ttcn|ttcn3|ttcnpp|ttl|txt|v|vb|vbs|vhd|vhdl|vtl|vue|webidl|xml|xquery|xsd|xsl|xu|xy|yaml|yml|ys|z80)$/i;
my $exactTextDocxPdfExtensionsNoPeriod = qr/^(1|2|3|4|4th|5|6|7|8|9|BUILD|R|apl|asc|asn|asn1|aspx|b|bash|bat|bf|bzl|c|cc|cfg|cgi|cl|clj|cljc|cljs|cljx|cmake|cob|coffee|conf|cpp|cpy|cql|cr|cs|css|cxx|cyp|cypher|d|dart|def|diff|docx|dtd|dyalog|dyl|dylan|e|ecl|edn|ejs|el|elm|erb|erl|f|f77|f90|f95|factor|feature|for|forth|fs|fth|fun|go|gradle|groovy|gss|h|haml|handlebars|hbs|hh|hpp|hs|htm|html|hx|hxml|hxx|in|ini|ino|intr|j2|jade|java|jinja|jinja2|jl|js|json|jsonld|jsp|jsx|ksh|kt|less|lhs|lisp|list|log|ls|ltx|lua|m|map|markdown|mbox|md|mkd|ml|mli|mll|mly|mm|mo|mps|msc|mscgen|mscin|msgenny|nb|nq|nsh|nsi|nt|nut|oz|p|pas|patch|pdf|pgp|php|php3|php4|php5|php7|phtml|pig|pl|pls|pm|pod|pp|pro|properties|proto|ps1|psd1|psm1|pug|pxd|pxi|py|pyw|pyx|q|r|rb|rq|rs|rst|s|sas|sass|scala|scm|scss|sh|sieve|sig|siv|slim|smackspec|sml|soy|sparql|spec|sql|ss|st|styl|sv|svg|svh|swift|t|tcl|tex|text|textile|toml|tpl|ts|tsx|ttcn|ttcn3|ttcnpp|ttl|txt|v|vb|vbs|vhd|vhdl|vtl|vue|webidl|xml|xquery|xsd|xsl|xu|xy|yaml|yml|ys|z80)$/i;

sub EndsWithTextExtension {
	my ($text) = @_;
	return($text =~ $textExtensions);
	}

sub EndsWithImageExtension {
	my ($text) = @_;
	return($text =~ $imageExtensions);
	}

sub EndsWithTextOrImageExtension {
	my ($text) = @_;
	return($text =~ $textExtensions || $text =~ $imageExtensions);	
	}
	
sub GetTextExtension {
	my ($text) = @_;
	my $result = ($text =~ $textExtensions) ? $1: '';
	return($result);
	}

sub GetImageExtension {
	my ($text) = @_;
	my $result = ($text =~ $imageExtensions) ? $1: '';
	return($result);
	}

sub GetTextOrImageExtension {
	my ($text) = @_;
	my $result = ($text =~ $textExtensions || $text =~ $imageExtensions) ? $1: '';
	return($result);
	}
	
sub EndsWithTextExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $textExtensionsNoPeriod);
	}

sub EndsWithImageExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $imageExtensionsNoPeriod);
	}

sub EndsWithTextOrImageExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $textExtensionsNoPeriod || $text =~ $imageExtensionsNoPeriod);	
	}

sub GetTextExtensionNoPeriod {
	my ($text) = @_;
	my $result = ($text =~ $textExtensionsNoPeriod) ? $1: '';
	return($result);
	}

sub GetImageExtensionNoPeriod {
	my ($text) = @_;
	my $result = ($text =~ $imageExtensionsNoPeriod) ? $1: '';
	return($result);
	}

sub GetTextOrImageExtensionNoPeriod {
	my ($text) = @_;
	my $result = ($text =~ $textExtensionsNoPeriod || $text =~ $imageExtensionsNoPeriod) ? $1: '';
	return($result);
	}

sub IsTextExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $exactTextExtensionsNoPeriod);	
	}

sub IsImageExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $exactImageExtensionsNoPeriod);		
	}

sub IsTextOrImageExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $exactTextExtensionsNoPeriod || $text =~ $exactImageExtensionsNoPeriod);		
	}

# Including docx and pdf:
sub EndsWithDocxPdfTextExtension {
	my ($text) = @_;
	return($text =~ $textDocxPdfExtensions);
	}

sub EndsWithTextDocxPdfOrImageExtension {
	my ($text) = @_;
	return($text =~ $textDocxPdfExtensions || $text =~ $imageExtensions);
	}

sub GetTextDocxPdfOrImageExtension {
	my ($text) = @_;
	my $result = ($text =~ $textDocxPdfExtensions || $text =~ $imageExtensions) ? $1: '';
	return($result);
	}

sub EndsWithTextDocxPdfExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $textDocxPdfExtensionsNoPeriod);
	}

sub EndsWithTextDocxPdfOrImageExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $textDocxPdfExtensionsNoPeriod || $text =~ $imageExtensionsNoPeriod);
	}

sub GetTextDocxPdfExtensionNoPeriod {
	my ($text) = @_;
	my $result = ($text =~ $textDocxPdfExtensionsNoPeriod) ? $1: '';
	return($result);
	}

sub GetTextDocxPdfOrImageExtensionNoPeriod {
	my ($text) = @_;
	my $result = ($text =~ $textDocxPdfExtensionsNoPeriod || $text =~ $imageExtensionsNoPeriod) ? $1: '';
	return($result);
	}

sub IsTextDocxPdfExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $exactTextDocxPdfExtensionsNoPeriod);
	}

sub IsTextDocxPdfOrImageExtensionNoPeriod {
	my ($text) = @_;
	return($text =~ $exactTextDocxPdfExtensionsNoPeriod || $text =~ $exactImageExtensionsNoPeriod);		
	}

# Extensions for all languages supported by CodeMirror.
my %extensionsForLanguage; # NOTE includes %popularExtensionsForLanguage

# Of those, the ones judged most popular (show at top of language dropdown).
my %popularExtensionsForLanguage;

$extensionsForLanguage{'APL'} = 'dyalog,apl';
$extensionsForLanguage{'ASN.1'} = 'asn,asn1';
$extensionsForLanguage{'ASP.NET'} = 'aspx';
$extensionsForLanguage{'Batch'} = 'bat';  # Added by hand, not handled by CodeMirror.
$extensionsForLanguage{'Brainf__k'} = 'b,bf';
$extensionsForLanguage{'C#'} = 'cs';
#$extensionsForLanguage{'C++'} = 'cpp,cc,c++,cxx,hpp,h,hh,hxx,h++';
$extensionsForLanguage{'C/C++'} = 'cpp,cc,c,cxx,hpp,h,hh,hxx';
$extensionsForLanguage{'CMake'} = 'cmake,in';
$extensionsForLanguage{'CQL'} = 'cql';
$extensionsForLanguage{'CSS'} = 'css';
$extensionsForLanguage{'Clojure'} = 'clj,cljc,cljx';
$extensionsForLanguage{'ClojureScript'} = 'cljs';
$extensionsForLanguage{'Closure Stylesheets'} = 'gss';
$extensionsForLanguage{'Cobol'} = 'cob,cpy';
$extensionsForLanguage{'CoffeeScript'} = 'coffee';
$extensionsForLanguage{'Common Lisp'} = 'cl,lisp,el';
$extensionsForLanguage{'Crystal'} = 'cr';
$extensionsForLanguage{'Cypher'} = 'cyp,cypher';
$extensionsForLanguage{'Cython'} = 'pyx,pxd,pxi';
$extensionsForLanguage{'D'} = 'd';
$extensionsForLanguage{'DTD'} = 'dtd';
$extensionsForLanguage{'Dart'} = 'dart';
$extensionsForLanguage{'Dylan'} = 'dylan,dyl,intr';
$extensionsForLanguage{'ECL'} = 'ecl';
$extensionsForLanguage{'Eiffel'} = 'e';
$extensionsForLanguage{'Elm'} = 'elm';
$extensionsForLanguage{'Embedded Javascript'} = 'ejs';
$extensionsForLanguage{'Embedded Ruby'} = 'erb';
$extensionsForLanguage{'Erlang'} = 'erl';
$extensionsForLanguage{'F#'} = 'fs';
$extensionsForLanguage{'Factor'} = 'factor';
$extensionsForLanguage{'Forth'} = 'forth,fth,4th';
$extensionsForLanguage{'Fortran'} = 'f,for,f77,f90,f95';
$extensionsForLanguage{'Gas'} = 's';
$extensionsForLanguage{'Gherkin'} = 'feature';
$extensionsForLanguage{'Go'} = 'go';
$extensionsForLanguage{'Groovy'} = 'groovy,gradle';
$extensionsForLanguage{'HAML'} = 'haml';
$extensionsForLanguage{'HTML'} = 'html,htm,handlebars,hbs';
$extensionsForLanguage{'HXML'} = 'hxml';
$extensionsForLanguage{'Haskell'} = 'hs';
$extensionsForLanguage{'Haskell (Literate)'} = 'lhs';
$extensionsForLanguage{'Haxe'} = 'hx';
$extensionsForLanguage{'IDL'} = 'pro';
$extensionsForLanguage{'JSON'} = 'json,map';
$extensionsForLanguage{'JSON-LD'} = 'jsonld';
$extensionsForLanguage{'JSX'} = 'jsx';
$extensionsForLanguage{'Java'} = 'java';
$extensionsForLanguage{'Java Server Pages'} = 'jsp';
$extensionsForLanguage{'JavaScript'} = 'js';
$extensionsForLanguage{'Jinja2'} = 'j2,jinja,jinja2';
$extensionsForLanguage{'Julia'} = 'jl';
$extensionsForLanguage{'Kotlin'} = 'kt';
$extensionsForLanguage{'LESS'} = 'less';
$extensionsForLanguage{'LaTeX'} = 'text,ltx,tex';
$extensionsForLanguage{'LiveScript'} = 'ls';
$extensionsForLanguage{'Lua'} = 'lua';
$extensionsForLanguage{'MUMPS'} = 'mps';
$extensionsForLanguage{'Markdown'} = 'markdown,md,mkd';
$extensionsForLanguage{'Mathematica'} = 'm,nb';
$extensionsForLanguage{'Modelica'} = 'mo';
$extensionsForLanguage{'NSIS'} = 'nsh,nsi';
$extensionsForLanguage{'NTriples'} = 'nt,nq';
$extensionsForLanguage{'OCaml'} = 'ml,mli,mll,mly';
$extensionsForLanguage{'Objective-C'} = 'm,mm';
$extensionsForLanguage{'Octave'} = 'm';
$extensionsForLanguage{'Oz'} = 'oz';
$extensionsForLanguage{'PDF'} = 'pdf';
$extensionsForLanguage{'PEG.js'} = 'jsonld';
$extensionsForLanguage{'PGP'} = 'asc,pgp,sig';
$extensionsForLanguage{'PHP'} = 'php,php3,php4,php5,php7,phtml';
$extensionsForLanguage{'PLSQL'} = 'pls';
$extensionsForLanguage{'Pascal'} = 'p,pas';
$extensionsForLanguage{'Perl'} = 'pl,pm,cgi,t,pod';
#$extensionsForLanguage{'Perl Test'} = 't'; # added by hand
#$extensionsForLanguage{'Perl Pod'} = 'pod'; # added by hand
$extensionsForLanguage{'Pig'} = 'pig';
$extensionsForLanguage{'Plain Text'} = 'txt,text,conf,def,list,log';
$extensionsForLanguage{'PowerShell'} = 'ps1,psd1,psm1';
$extensionsForLanguage{'Properties files'} = 'properties,ini,in';
$extensionsForLanguage{'ProtoBuf'} = 'proto';
$extensionsForLanguage{'Pug'} = 'jade,pug';
$extensionsForLanguage{'Puppet'} = 'pp';
$extensionsForLanguage{'Python'} = 'BUILD,bzl,py,pyw';
$extensionsForLanguage{'Q'} = 'q';
$extensionsForLanguage{'R'} = 'r,R';
$extensionsForLanguage{'RPM Spec'} = 'spec';
$extensionsForLanguage{'Ruby'} = 'rb';
$extensionsForLanguage{'Rust'} = 'rs';
$extensionsForLanguage{'SAS'} = 'sas';
$extensionsForLanguage{'SCSS'} = 'scss';
$extensionsForLanguage{'SML'} = 'sml,sig,fun,smackspec';
$extensionsForLanguage{'SPARQL'} = 'rq,sparql';
$extensionsForLanguage{'SQL'} = 'sql';
$extensionsForLanguage{'Sass'} = 'sass';
$extensionsForLanguage{'Scala'} = 'scala';
$extensionsForLanguage{'Scheme'} = 'scm,ss';
$extensionsForLanguage{'Shell'} = 'sh,ksh,bash';
$extensionsForLanguage{'Sieve'} = 'siv,sieve';
$extensionsForLanguage{'Slim'} = 'slim';
$extensionsForLanguage{'Smalltalk'} = 'st';
$extensionsForLanguage{'Smarty'} = 'tpl';
$extensionsForLanguage{'Soy'} = 'soy';
$extensionsForLanguage{'Squirrel'} = 'nut';
$extensionsForLanguage{'Stylus'} = 'styl';
$extensionsForLanguage{'Swift'} = 'swift';
$extensionsForLanguage{'SystemVerilog'} = 'v,sv,svh';
$extensionsForLanguage{'TOML'} = 'toml';
$extensionsForLanguage{'TTCN'} = 'ttcn,ttcn3,ttcnpp';
$extensionsForLanguage{'TTCN_CFG'} = 'cfg';
$extensionsForLanguage{'Tcl'} = 'tcl';
$extensionsForLanguage{'Textile'} = 'textile';
$extensionsForLanguage{'Turtle'} = 'ttl';
$extensionsForLanguage{'TypeScript'} = 'ts';
$extensionsForLanguage{'TypeScript-JSX'} = 'tsx';
$extensionsForLanguage{'VB.NET'} = 'vb';
$extensionsForLanguage{'VBScript'} = 'vbs';
$extensionsForLanguage{'VHDL'} = 'vhd,vhdl';
$extensionsForLanguage{'Velocity'} = 'vtl';
$extensionsForLanguage{'Verilog'} = 'v';
$extensionsForLanguage{'Vue.js Component'} = 'vue';
$extensionsForLanguage{'Web IDL'} = 'webidl';
$extensionsForLanguage{'Word'} = 'docx';
$extensionsForLanguage{'XML'} = 'xml,xsl,xsd,svg';
$extensionsForLanguage{'XQuery'} = 'xy,xquery';
$extensionsForLanguage{'YAML'} = 'yaml,yml';
$extensionsForLanguage{'Yacas'} = 'ys';
$extensionsForLanguage{'Z80'} = 'z80';
$extensionsForLanguage{'diff'} = 'diff,patch';
$extensionsForLanguage{'edn'} = 'edn';
$extensionsForLanguage{'mbox'} = 'mbox';
$extensionsForLanguage{'mscgen'} = 'mscgen,mscin,msc';
$extensionsForLanguage{'msgenny'} = 'msgenny';
$extensionsForLanguage{'reStructuredText'} = 'rst';
$extensionsForLanguage{'troff'} = '1,2,3,4,5,6,7,8,9';
$extensionsForLanguage{'xu'} = 'xu';

# Note these duplicate entries above.
$popularExtensionsForLanguage{'ASP.NET'} = 'aspx';
$popularExtensionsForLanguage{'Batch'} = 'bat';
$popularExtensionsForLanguage{'C#'} = 'cs';
$popularExtensionsForLanguage{'C/C++'} = 'cpp,cc,c,cxx,hpp,h,hh,hxx';
$popularExtensionsForLanguage{'CSS'} = 'css';
$popularExtensionsForLanguage{'Go'} = 'go';
$popularExtensionsForLanguage{'HTML'} = 'html,htm,handlebars,hbs';
$popularExtensionsForLanguage{'Java'} = 'java';
$popularExtensionsForLanguage{'JavaScript'} = 'js';
#$popularExtensionsForLanguage{'Objective-C'} = 'm,mm';
$popularExtensionsForLanguage{'Perl'} = 'pl,pm,cgi,t,pod';
$popularExtensionsForLanguage{'Plain Text'} = 'txt,text,conf,def,list,log';
$popularExtensionsForLanguage{'Python'} = 'BUILD,bzl,py,pyw';
$popularExtensionsForLanguage{'Ruby'} = 'rb';
$popularExtensionsForLanguage{'SQL'} = 'sql';
$popularExtensionsForLanguage{'VB.NET'} = 'vb';
$popularExtensionsForLanguage{'VBScript'} = 'vbs';


sub ExtensionsForLanguageHashRef {
	return(\%extensionsForLanguage);
	}

sub PopularExtensionsForLanguageHashRef {
	return(\%popularExtensionsForLanguage);
	}

# Total number of (unique) extensions, to all determining if all extensions have been selected.
# As of last count there are 226.
sub NumExtensions {
	my %uniqueExtensions;
	foreach my $key (keys %extensionsForLanguage)
		{
		my $value = $extensionsForLanguage{$key};
		my @exts = split(/,/, $value);
		for (my $i = 0; $i < @exts; ++$i)
			{
			$uniqueExtensions{$exts[$i]} += 1;
			}
		}
	
	my $result = keys %uniqueExtensions;
	
	return($result);
	}

use ExportAbove;
return 1;
