# holidays.pm: statutory Ontario, Canada holidays. Use holiday() with Date::Business.
# eg
# my $thisDay = '20110102'; # YYYYMMDD Jan 2, 2011
# my $thisDate = new Date::Business(DATE => $thisDay, HOLIDAY => \&holiday);
# my $thatDay = '20101221';
# my $thatDate = new Date::Business(DATE => $thatDay, HOLIDAY => \&holiday);
# my $diff = $thisDate->diffb($thatDate); # business days, excluding holidays.
# Dates generated by C:\perlprogs\mgs\amapceo4x_holiday_generator.pl $kOutputStyle = 'perl'.

package holidays;
use warnings;
require Exporter;
use Exporter qw(import);

use utf8;

BEGIN
{

{ # Holidays.
my @holidays;
my %holidaysHasher;

sub InitHolidays {
	@holidays = ();
	@holidaynames = ();
push @holidays, '20080101';  push @holidaynames, 'New Year';
push @holidays, '20080218';  push @holidaynames, 'Family Day';
push @holidays, '20080321';  push @holidaynames, 'Good Friday';
push @holidays, '20080324';  push @holidaynames, 'Easter Monday';
push @holidays, '20080519';  push @holidaynames, 'Victoria Day';
push @holidays, '20080701';  push @holidaynames, 'Canada Day';
push @holidays, '20080804';  push @holidaynames, 'Civic';
push @holidays, '20080901';  push @holidaynames, 'Labour Day';
push @holidays, '20081013';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20081111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20081225';  push @holidaynames, 'Christmas';
push @holidays, '20081226';  push @holidaynames, 'Boxing Day';
push @holidays, '20090101';  push @holidaynames, 'New Year';
push @holidays, '20090216';  push @holidaynames, 'Family Day';
push @holidays, '20090410';  push @holidaynames, 'Good Friday';
push @holidays, '20090413';  push @holidaynames, 'Easter Monday';
push @holidays, '20090518';  push @holidaynames, 'Victoria Day';
push @holidays, '20090701';  push @holidaynames, 'Canada Day';
push @holidays, '20090803';  push @holidaynames, 'Civic';
push @holidays, '20090907';  push @holidaynames, 'Labour Day';
push @holidays, '20091012';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20091111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20091225';  push @holidaynames, 'Christmas';
push @holidays, '20091228';  push @holidaynames, 'Boxing Day';
push @holidays, '20100101';  push @holidaynames, 'New Year';
push @holidays, '20100215';  push @holidaynames, 'Family Day';
push @holidays, '20100402';  push @holidaynames, 'Good Friday';
push @holidays, '20100405';  push @holidaynames, 'Easter Monday';
push @holidays, '20100524';  push @holidaynames, 'Victoria Day';
push @holidays, '20100701';  push @holidaynames, 'Canada Day';
push @holidays, '20100802';  push @holidaynames, 'Civic';
push @holidays, '20100906';  push @holidaynames, 'Labour Day';
push @holidays, '20101011';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20101111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20101224';  push @holidaynames, 'Christmas';
push @holidays, '20101227';  push @holidaynames, 'Boxing Day';
push @holidays, '20110103';  push @holidaynames, 'New Year';
push @holidays, '20110221';  push @holidaynames, 'Family Day';
push @holidays, '20110422';  push @holidaynames, 'Good Friday';
push @holidays, '20110425';  push @holidaynames, 'Easter Monday';
push @holidays, '20110523';  push @holidaynames, 'Victoria Day';
push @holidays, '20110701';  push @holidaynames, 'Canada Day';
push @holidays, '20110801';  push @holidaynames, 'Civic';
push @holidays, '20110905';  push @holidaynames, 'Labour Day';
push @holidays, '20111010';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20111111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20111223';  push @holidaynames, 'Christmas';
push @holidays, '20111226';  push @holidaynames, 'Boxing Day';
push @holidays, '20120102';  push @holidaynames, 'New Year';
push @holidays, '20120220';  push @holidaynames, 'Family Day';
push @holidays, '20120406';  push @holidaynames, 'Good Friday';
push @holidays, '20120409';  push @holidaynames, 'Easter Monday';
push @holidays, '20120521';  push @holidaynames, 'Victoria Day';
push @holidays, '20120702';  push @holidaynames, 'Canada Day';
push @holidays, '20120806';  push @holidaynames, 'Civic';
push @holidays, '20120903';  push @holidaynames, 'Labour Day';
push @holidays, '20121008';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20121112';  push @holidaynames, 'Remembrance Day';
push @holidays, '20121225';  push @holidaynames, 'Christmas';
push @holidays, '20121226';  push @holidaynames, 'Boxing Day';
push @holidays, '20130101';  push @holidaynames, 'New Year';
push @holidays, '20130218';  push @holidaynames, 'Family Day';
push @holidays, '20130329';  push @holidaynames, 'Good Friday';
push @holidays, '20130401';  push @holidaynames, 'Easter Monday';
push @holidays, '20130520';  push @holidaynames, 'Victoria Day';
push @holidays, '20130701';  push @holidaynames, 'Canada Day';
push @holidays, '20130805';  push @holidaynames, 'Civic';
push @holidays, '20130902';  push @holidaynames, 'Labour Day';
push @holidays, '20131014';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20131111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20131225';  push @holidaynames, 'Christmas';
push @holidays, '20131226';  push @holidaynames, 'Boxing Day';
push @holidays, '20140101';  push @holidaynames, 'New Year';
push @holidays, '20140217';  push @holidaynames, 'Family Day';
push @holidays, '20140418';  push @holidaynames, 'Good Friday';
push @holidays, '20140421';  push @holidaynames, 'Easter Monday';
push @holidays, '20140519';  push @holidaynames, 'Victoria Day';
push @holidays, '20140701';  push @holidaynames, 'Canada Day';
push @holidays, '20140804';  push @holidaynames, 'Civic';
push @holidays, '20140901';  push @holidaynames, 'Labour Day';
push @holidays, '20141013';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20141111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20141225';  push @holidaynames, 'Christmas';
push @holidays, '20141226';  push @holidaynames, 'Boxing Day';
push @holidays, '20150101';  push @holidaynames, 'New Year';
push @holidays, '20150216';  push @holidaynames, 'Family Day';
push @holidays, '20150403';  push @holidaynames, 'Good Friday';
push @holidays, '20150406';  push @holidaynames, 'Easter Monday';
push @holidays, '20150518';  push @holidaynames, 'Victoria Day';
push @holidays, '20150701';  push @holidaynames, 'Canada Day';
push @holidays, '20150803';  push @holidaynames, 'Civic';
push @holidays, '20150907';  push @holidaynames, 'Labour Day';
push @holidays, '20151012';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20151111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20151225';  push @holidaynames, 'Christmas';
push @holidays, '20151228';  push @holidaynames, 'Boxing Day';
push @holidays, '20160101';  push @holidaynames, 'New Year';
push @holidays, '20160215';  push @holidaynames, 'Family Day';
push @holidays, '20160325';  push @holidaynames, 'Good Friday';
push @holidays, '20160328';  push @holidaynames, 'Easter Monday';
push @holidays, '20160523';  push @holidaynames, 'Victoria Day';
push @holidays, '20160701';  push @holidaynames, 'Canada Day';
push @holidays, '20160801';  push @holidaynames, 'Civic';
push @holidays, '20160905';  push @holidaynames, 'Labour Day';
push @holidays, '20161010';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20161111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20161223';  push @holidaynames, 'Christmas';
push @holidays, '20161226';  push @holidaynames, 'Boxing Day';
push @holidays, '20170102';  push @holidaynames, 'New Year';
push @holidays, '20170220';  push @holidaynames, 'Family Day';
push @holidays, '20170414';  push @holidaynames, 'Good Friday';
push @holidays, '20170417';  push @holidaynames, 'Easter Monday';
push @holidays, '20170522';  push @holidaynames, 'Victoria Day';
push @holidays, '20170703';  push @holidaynames, 'Canada Day';
push @holidays, '20170807';  push @holidaynames, 'Civic';
push @holidays, '20170904';  push @holidaynames, 'Labour Day';
push @holidays, '20171009';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20171113';  push @holidaynames, 'Remembrance Day';
push @holidays, '20171225';  push @holidaynames, 'Christmas';
push @holidays, '20171226';  push @holidaynames, 'Boxing Day';
push @holidays, '20180101';  push @holidaynames, 'New Year';
push @holidays, '20180219';  push @holidaynames, 'Family Day';
push @holidays, '20180330';  push @holidaynames, 'Good Friday';
push @holidays, '20180402';  push @holidaynames, 'Easter Monday';
push @holidays, '20180521';  push @holidaynames, 'Victoria Day';
push @holidays, '20180702';  push @holidaynames, 'Canada Day';
push @holidays, '20180806';  push @holidaynames, 'Civic';
push @holidays, '20180903';  push @holidaynames, 'Labour Day';
push @holidays, '20181008';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20181112';  push @holidaynames, 'Remembrance Day';
push @holidays, '20181225';  push @holidaynames, 'Christmas';
push @holidays, '20181226';  push @holidaynames, 'Boxing Day';
push @holidays, '20190101';  push @holidaynames, 'New Year';
push @holidays, '20190218';  push @holidaynames, 'Family Day';
push @holidays, '20190419';  push @holidaynames, 'Good Friday';
push @holidays, '20190422';  push @holidaynames, 'Easter Monday';
push @holidays, '20190520';  push @holidaynames, 'Victoria Day';
push @holidays, '20190701';  push @holidaynames, 'Canada Day';
push @holidays, '20190805';  push @holidaynames, 'Civic';
push @holidays, '20190902';  push @holidaynames, 'Labour Day';
push @holidays, '20191014';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20191111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20191225';  push @holidaynames, 'Christmas';
push @holidays, '20191226';  push @holidaynames, 'Boxing Day';
push @holidays, '20200101';  push @holidaynames, 'New Year';
push @holidays, '20200217';  push @holidaynames, 'Family Day';
push @holidays, '20200410';  push @holidaynames, 'Good Friday';
push @holidays, '20200413';  push @holidaynames, 'Easter Monday';
push @holidays, '20200518';  push @holidaynames, 'Victoria Day';
push @holidays, '20200701';  push @holidaynames, 'Canada Day';
push @holidays, '20200803';  push @holidaynames, 'Civic';
push @holidays, '20200907';  push @holidaynames, 'Labour Day';
push @holidays, '20201012';  push @holidaynames, 'Thanksgiving Day';
push @holidays, '20201111';  push @holidaynames, 'Remembrance Day';
push @holidays, '20201225';  push @holidaynames, 'Christmas';
push @holidays, '20201228';  push @holidaynames, 'Boxing Day';
push @holidays, '20210101'; push @holidaynames, 'New Year';
push @holidays, '20210215'; push @holidaynames, 'Family Day';
push @holidays, '20210402'; push @holidaynames, 'Good Friday';
push @holidays, '20210405'; push @holidaynames, 'Easter Monday';
push @holidays, '20210524'; push @holidaynames, 'Victoria Day';
push @holidays, '20210701'; push @holidaynames, 'Canada Day';
push @holidays, '20210802'; push @holidaynames, 'Civic';
push @holidays, '20210906'; push @holidaynames, 'Labour Day';
push @holidays, '20211011'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20211111'; push @holidaynames, 'Remembrance Day';
push @holidays, '20211224'; push @holidaynames, 'Christmas';
push @holidays, '20211227'; push @holidaynames, 'Boxing Day';
push @holidays, '20220103'; push @holidaynames, 'New Year';
push @holidays, '20220221'; push @holidaynames, 'Family Day';
push @holidays, '20220415'; push @holidaynames, 'Good Friday';
push @holidays, '20220418'; push @holidaynames, 'Easter Monday';
push @holidays, '20220523'; push @holidaynames, 'Victoria Day';
push @holidays, '20220701'; push @holidaynames, 'Canada Day';
push @holidays, '20220801'; push @holidaynames, 'Civic';
push @holidays, '20220905'; push @holidaynames, 'Labour Day';
push @holidays, '20221010'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20221111'; push @holidaynames, 'Remembrance Day';
push @holidays, '20221223'; push @holidaynames, 'Christmas';
push @holidays, '20221226'; push @holidaynames, 'Boxing Day';
push @holidays, '20230102'; push @holidaynames, 'New Year';
push @holidays, '20230220'; push @holidaynames, 'Family Day';
push @holidays, '20230407'; push @holidaynames, 'Good Friday';
push @holidays, '20230410'; push @holidaynames, 'Easter Monday';
push @holidays, '20230522'; push @holidaynames, 'Victoria Day';
push @holidays, '20230703'; push @holidaynames, 'Canada Day';
push @holidays, '20230807'; push @holidaynames, 'Civic';
push @holidays, '20230904'; push @holidaynames, 'Labour Day';
push @holidays, '20231009'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20231113'; push @holidaynames, 'Remembrance Day';
push @holidays, '20231225'; push @holidaynames, 'Christmas';
push @holidays, '20231226'; push @holidaynames, 'Boxing Day';
push @holidays, '20240101'; push @holidaynames, 'New Year';
push @holidays, '20240219'; push @holidaynames, 'Family Day';
push @holidays, '20240329'; push @holidaynames, 'Good Friday';
push @holidays, '20240401'; push @holidaynames, 'Easter Monday';
push @holidays, '20240520'; push @holidaynames, 'Victoria Day';
push @holidays, '20240701'; push @holidaynames, 'Canada Day';
push @holidays, '20240805'; push @holidaynames, 'Civic';
push @holidays, '20240902'; push @holidaynames, 'Labour Day';
push @holidays, '20241014'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20241111'; push @holidaynames, 'Remembrance Day';
push @holidays, '20241225'; push @holidaynames, 'Christmas';
push @holidays, '20241226'; push @holidaynames, 'Boxing Day';
push @holidays, '20250101'; push @holidaynames, 'New Year';
push @holidays, '20250217'; push @holidaynames, 'Family Day';
push @holidays, '20250418'; push @holidaynames, 'Good Friday';
push @holidays, '20250421'; push @holidaynames, 'Easter Monday';
push @holidays, '20250519'; push @holidaynames, 'Victoria Day';
push @holidays, '20250701'; push @holidaynames, 'Canada Day';
push @holidays, '20250804'; push @holidaynames, 'Civic';
push @holidays, '20250901'; push @holidaynames, 'Labour Day';
push @holidays, '20251013'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20251111'; push @holidaynames, 'Remembrance Day';
push @holidays, '20251225'; push @holidaynames, 'Christmas';
push @holidays, '20251226'; push @holidaynames, 'Boxing Day';
push @holidays, '20260101'; push @holidaynames, 'New Year';
push @holidays, '20260216'; push @holidaynames, 'Family Day';
push @holidays, '20260403'; push @holidaynames, 'Good Friday';
push @holidays, '20260406'; push @holidaynames, 'Easter Monday';
push @holidays, '20260518'; push @holidaynames, 'Victoria Day';
push @holidays, '20260701'; push @holidaynames, 'Canada Day';
push @holidays, '20260803'; push @holidaynames, 'Civic';
push @holidays, '20260907'; push @holidaynames, 'Labour Day';
push @holidays, '20261012'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20261111'; push @holidaynames, 'Remembrance Day';
push @holidays, '20261225'; push @holidaynames, 'Christmas';
push @holidays, '20261228'; push @holidaynames, 'Boxing Day';
push @holidays, '20270101'; push @holidaynames, 'New Year';
push @holidays, '20270215'; push @holidaynames, 'Family Day';
push @holidays, '20270326'; push @holidaynames, 'Good Friday';
push @holidays, '20270329'; push @holidaynames, 'Easter Monday';
push @holidays, '20270524'; push @holidaynames, 'Victoria Day';
push @holidays, '20270701'; push @holidaynames, 'Canada Day';
push @holidays, '20270802'; push @holidaynames, 'Civic';
push @holidays, '20270906'; push @holidaynames, 'Labour Day';
push @holidays, '20271011'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20271111'; push @holidaynames, 'Remembrance Day';
push @holidays, '20271224'; push @holidaynames, 'Christmas';
push @holidays, '20271227'; push @holidaynames, 'Boxing Day';
push @holidays, '20280103'; push @holidaynames, 'New Year';
push @holidays, '20280221'; push @holidaynames, 'Family Day';
push @holidays, '20280414'; push @holidaynames, 'Good Friday';
push @holidays, '20280417'; push @holidaynames, 'Easter Monday';
push @holidays, '20280522'; push @holidaynames, 'Victoria Day';
push @holidays, '20280703'; push @holidaynames, 'Canada Day';
push @holidays, '20280807'; push @holidaynames, 'Civic';
push @holidays, '20280904'; push @holidaynames, 'Labour Day';
push @holidays, '20281009'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20281113'; push @holidaynames, 'Remembrance Day';
push @holidays, '20281225'; push @holidaynames, 'Christmas';
push @holidays, '20281226'; push @holidaynames, 'Boxing Day';
push @holidays, '20290101'; push @holidaynames, 'New Year';
push @holidays, '20290219'; push @holidaynames, 'Family Day';
push @holidays, '20290330'; push @holidaynames, 'Good Friday';
push @holidays, '20290402'; push @holidaynames, 'Easter Monday';
push @holidays, '20290521'; push @holidaynames, 'Victoria Day';
push @holidays, '20290702'; push @holidaynames, 'Canada Day';
push @holidays, '20290806'; push @holidaynames, 'Civic';
push @holidays, '20290903'; push @holidaynames, 'Labour Day';
push @holidays, '20291008'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20291112'; push @holidaynames, 'Remembrance Day';
push @holidays, '20291225'; push @holidaynames, 'Christmas';
push @holidays, '20291226'; push @holidaynames, 'Boxing Day';
push @holidays, '20300101'; push @holidaynames, 'New Year';
push @holidays, '20300218'; push @holidaynames, 'Family Day';
push @holidays, '20300419'; push @holidaynames, 'Good Friday';
push @holidays, '20300422'; push @holidaynames, 'Easter Monday';
push @holidays, '20300520'; push @holidaynames, 'Victoria Day';
push @holidays, '20300701'; push @holidaynames, 'Canada Day';
push @holidays, '20300805'; push @holidaynames, 'Civic';
push @holidays, '20300902'; push @holidaynames, 'Labour Day';
push @holidays, '20301014'; push @holidaynames, 'ThanksgivingDay';
push @holidays, '20301111'; push @holidaynames, 'Remembrance Day';
push @holidays, '20301225'; push @holidaynames, 'Christmas';
push @holidays, '20301226'; push @holidaynames, 'Boxing Day';
	
	for (my $i = 0; $i < @holidays; ++$i)
		{
		$holidaysHasher{$holidays[$i]} = $holidaynames[$i];
		}
	}

sub holiday {
    my ($strt, $nd) = @_;
    
    my $numHolidays = 0;
    foreach my $h (@holidays)
		{
        $numHolidays++ if ($strt le $h && $nd ge $h);
    	}
    return $numHolidays;
	}
	
sub IsAHolidayYYYYMMDD {
	my ($ymd) = @_;
	my $result = defined($holidaysHasher{$ymd}) ? 1 : 0;
	return $result;
	}

sub HolidayNameForYYYYMMDD {
	my ($ymd) = @_;
	my $result = defined($holidaysHasher{$ymd}) ? $holidaysHasher{$ymd} : '';
	return $result;
	}
} # Holidays.

use ExportAbove;

InitHolidays();

} # BEGIN
return 1;
